### PR TITLE
WIP: Add support for completion-at-point-functions and company-mode

### PR DESCRIPTION
**Pull request by TatriX**
Hi!
This PR introduces support for new builtin Emacs completion mechanism `completion-at-point-functions`.
I'm also planning to add method completion support.

### CODE REVIEW

**Comment by widp** [comment]
@mlang I haven't setup emacs on my new system could you please review this. Thanks a bunch

**Comment by TatriX** [comment]
I'm going to add method completion support, but it will take some time. I'm trying to get my head around implementation details, in particular about protocol used with `mkfifo`.

**Comment by mlang** [comment]
Thanks!  This is one step towards eliminating sclang-browser.el, which is great!

**Comment by TatriX** [comment]
> Thanks! This is one step towards eliminating sclang-browser.el, which is great!

Can you share your thoughts? I could help with eliminating things perhaps ;)

**Comment by mlang** [comment]
> Can you share your thoughts? I could help with eliminating things perhaps ;)

sclang-browser.el is currently used to
1. display completions
2. disambiguate between class files when using C-c : to jump to a definition

This PR will eliminate use-case #1.

If Emacs has a better way to present a menu (which will also work in
emacs -nw) I would like to see use case #2 eliminated as well, since
sclang-browser.el feels quite like a hack.

**Comment by TatriX** [comment]
I also plan to integrate `xref`, the built-in mechanism for  `go to definition`. It also resolves (2) as it can show candidates.

**Comment by russelldb** [comment]
Thanks for this, any word on how to use it? Or is it just the default way to complete a method now?

**Comment by TatriX** [comment]
It should work out of the box with the default Emacs completion mechanism.
By default it's `C-M-i` (same as `M-tab`) which uses `complete-symbol`. If you are using `company-mode` it should as well work out of the box.

**Pull request merged**
