### PR TITLE
El files fix

### PR DESCRIPTION
**Pull request by widp**
fixes path to sc help files.
Installs *.el files in addition to byte compiled elisp files.

### CODE REVIEW

**Comment by brianlheim** [comment]
Hey @widp, I would be happy to review this if you can describe what problems it's solving to a non emacs user :) I don't see any open tickets related to this.

**Comment by widp** [comment]
@brianlheim I've changed the build script so that emacs lisp source code gets installed along with the bytecode. This is how most emacs packages behave (installing both *.elc and *.el files).

Another change that I've made is to point to the correct help directory. All  schelp files are installed in PATH/HelpSource instead of PATH/Help , so I've updated the corresponding entry .

**Comment by brianlheim** [comment]
> Another change that I've made is to point to the correct help directory. All schelp files are installed in PATH/HelpSource instead of PATH/Help , so I've updated the corresponding entry .

But the files are compiled into HTML and stored in Help, right? Do you prefer to browse them in the unrendered format with emacs?

**Comment by widp** [comment]
@brianlheim  
I might have to spend some more time understanding the help system with emacs, since it is broken. I've reverted that commit.

**Comment by brianlheim** [comment]
All right! Thanks!

**Pull request merged**
